### ISSUE TITLE
GSA - Per Diem Rates API - javax.net.ssl.SSLKeyException: Hostname verification failed

### ISSUE THREAD

**Issue by JDEKid** [GSA/GSA-APIs#57]
We are trying to call the Per Diem rates API, but get an error at run time. Looking for any clues/pointers as to what could be causing the issue and/or shat can be tried to resolve this.

I am trying the call from a Java program running within JDeveloper - 12.2.1.0 (WLS 12.2.1.0).

<Feb 20, 2019 6:16:00 PM PST> <Warning> <Security> <BEA-090504> <Certificate chain received from inventory.data.gov - 34.193.244.109 failed hostname verification check. Certificate contained *.data.gov but check expected inventory.data.gov> 
javax.net.ssl.SSLKeyException: Hostname verification failed: HostnameVerifier=weblogic.security.utils.SSLWLSHostnameVerifier, hostname=inventory.data.gov.
	at weblogic.security.SSL.jsseadapter.JaSSLEngine.doPostHandshake(JaSSLEngine.java:677)
	at weblogic.security.SSL.jsseadapter.JaSSLEngine.doAction(JaSSLEngine.java:748)
	at weblogic.security.SSL.jsseadapter.JaSSLEngine.unwrap(JaSSLEngine.java:132)
	at weblogic.socket.JSSEFilterImpl.unwrap(JSSEFilterImpl.java:611)
	at weblogic.socket.JSSEFilterImpl.unwrapAndHandleResults(JSSEFilterImpl.java:515)
	at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:98)
	at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:77)
	at weblogic.socket.JSSESocket.startHandshake(JSSESocket.java:240)
	at weblogic.net.http.HttpsClient.New(HttpsClient.java:574)
	at weblogic.net.http.HttpsClient.New(HttpsClient.java:545)
	at weblogic.net.http.HttpsURLConnection.connect(HttpsURLConnection.java:230)
	at weblogic.net.http.HttpURLConnection.getInputStream(HttpURLConnection.java:685)
	at weblogic.net.http.SOAPHttpsURLConnection.getInputStream(SOAPHttpsURLConnection.java:41)
	at hit.e1.bssv.J5609E11.HIT_PerDiem_Processor.HIT_fetchPerDiemRates(HIT_PerDiem_Processor.java:261)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at oracle.e1.bssvfoundation.impl.jdenet.CallSBFHandler.callSBF(Unknown Source)
	at oracle.e1.bssvfoundation.impl.jdenet.CallSBFMsgHandler.process(Unknown Source)
	at oracle.e1.bssvfoundation.impl.jdenet.SBFServerJavaKernel.process(Unknown Source)
	at com.jdedwards.system.net.ProcessKernel.run(Unknown Source)

Thanks,
JDE Kid

**Comment by adborden** [comment]
Thanks for reporting this. Am I correct that you're hitting the inventory.data.gov API described [here](https://www.gsa.gov/technology/government-it-initiatives/digital-strategy/per-diem-apis/per-diem-api)?

inventory.data.gov uses a wildcard certificate (*.data.gov). Unfortunately, I'm not familiar with Weblogic or JDeveloper. After a quick web search, it looks like the default Weblogic verifier does not allow wildcard certificates. It looks like you can change this behavior, though. You want to use the `weblogic.security.utils.SSLWLSWildcardHostnameVerifier` as a custom verifier in Weblogic. The proces is described [here](https://www.albinsblog.com/2014/03/wildcard-ssl-hostnameverifier-in.html).

Hope this helps.

**Comment by JDEKid** [comment]
Aaron,

You are right about hitting the inventory.data.gov API.

I tried the solution suggested on the link that you sent, and the solution looks good. i just have to do some cross checks to see if it impacts anything else.

Thank you! You are the best!!

**Comment by Ryandaydev** [comment]
Appears to be answered and acknowledged. Closing issue.
