### ISSUE TITLE
Per Diem API - Get "java.io.IOException: An existing connection was forcibly closed by the remote host"

### ISSUE THREAD

**Issue by JDEKid** [GSA/GSA-APIs#62]

**Comment by JDEKid** [comment]
We get the following error when trying to invoke the Per Diem API to get rates.

java.io.IOException: An existing connection was forcibly closed by the remote host

We are using Weblogic Server 12.1.3.0.0 for the program that makes the call to the Per Diem API.

The port on our server is open to make calls out.

Thanks.

java.io.IOException: An existing connection was forcibly closed by the remote host
               at sun.nio.ch.SocketDispatcher.readv0(Native Method)
               at sun.nio.ch.SocketDispatcher.readv(SocketDispatcher.java:47)
               at sun.nio.ch.IOUtil.read(IOUtil.java:278)
               at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:440)
               at weblogic.socket.NIOSocketMuxer$NIOInputStream.readInternal(NIOSocketMuxer.java:803)
               at weblogic.socket.NIOSocketMuxer$NIOInputStream.read(NIOSocketMuxer.java:745)
               at weblogic.socket.NIOSocketMuxer$NIOInputStream.read(NIOSocketMuxer.java:728)
               at weblogic.socket.JSSEFilterImpl.readFromNetwork(JSSEFilterImpl.java:462)
               at weblogic.socket.JSSEFilterImpl.handleUnwrapResults(JSSEFilterImpl.java:634)
               at weblogic.socket.JSSEFilterImpl.unwrapAndHandleResults(JSSEFilterImpl.java:515)
               at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:96)
               at weblogic.socket.JSSEFilterImpl.doHandshake(JSSEFilterImpl.java:75)
               at weblogic.socket.JSSESocket.startHandshake(JSSESocket.java:219)
               at weblogic.net.http.HttpsClient.New(HttpsClient.java:563)
               at weblogic.net.http.HttpsURLConnection.getHttpClient(HttpsURLConnection.java:332)
               at weblogic.net.http.HttpURLConnection.getInputStream(HttpURLConnection.java:711)
               at weblogic.net.http.SOAPHttpsURLConnection.getInputStream(SOAPHttpsURLConnection.java:37)
               at hittgc.e1.bssv.J5609E11.HITT_PerDiem_Processor.HITT_fetchPerDiemRates(Unknown Source)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:498)
               at oracle.e1.bssvfoundation.impl.jdenet.CallSBFHandler.callSBF(Unknown Source)
               at oracle.e1.bssvfoundation.impl.jdenet.CallSBFMsgHandler.process(Unknown Source)
               at oracle.e1.bssvfoundation.impl.jdenet.SBFServerJavaKernel.process(Unknown Source)
               at com.jdedwards.system.net.ProcessKernel.run(Unknown Source)

**Comment by JDEKid** [comment]
Sorry, clicked on Close issue by mistake.

**Comment by adborden** [comment]
Thanks for opening this issue. I assume this is the request?

https://inventory.data.gov/api/action/datastore_search?resource_id=8ea44bc4-22ba-4386-b84c-1494ab28964b&limit=1&filters=%7B%22FiscalYear%22:%222019%22,%22State%22:%22VA%22,%22City%22:%22Falls%20Church%22,%22Zip%22:%2222042%22%7D

Usually this is a temporary error where a connection is interrupted. How often are you seeing this error? Is it every time you make a request? Is it only specific to these query parameters? How many requests are you making? As far as I can tell, the API is responding correctly with data.

There are a number of reasons why this could be happening. It's possible there was a network hiccup and the connection was reset. You could have made a request while a server was upgrading, interrupting the connection. In most cases, it's temporary and you should [back-off](https://en.wikipedia.org/wiki/Exponential_backoff) and retry.

**Comment by JDEKid** [comment]
Hi Aaron,

Thanks for the response. 

Q. How often are you seeing this error? 
A. Every time the service is called.

Q. Is it only specific to these query parameters?
A. No. The result is the same across any combination of parameters.

Q. How many requests are you making?
A. It doesn't matter. The result is the same for one or multiple calls.

Q. It's possible there was a network hiccup and the connection was reset. You could have made a request while a server was upgrading, interrupting the connection. In most cases, it's temporary and you should back-off and retry.
A. We have been trying this for a few weeks now, and the result has been consistent.

**Comment by JDEKid** [comment]
About how many requests are going to the API, please let me know if there is a limit to the number of calls that can be made per second/minute/hour.

Thanks.

**Comment by adborden** [comment]
We don't have any specific rate limiting in place that I am aware. If you are seeing this error on every request, then something else is at play. From the machine that you are running this code, are you able to open that URL with another tool? Maybe a web browser or curl?

I notice in your stack trace `weblogic.net.http.SOAPHttpsURLConnection`, but this API is JSON based, not SOAP. Are you sure you're using the right method to fetch from the API?

**Comment by JDEKid** [comment]
Found the issue. It was something about the version of Weblogic Server that we were trying it from - 12.1.3. 

Upgraded to 12.2.1.3 and it works well now.

Thanks!
